// deno-lint-ignore-file no-explicit-any
/**
 * h — The createElement function for @fobx/jsx.
 *
 * Produces real DOM nodes (not virtual), wiring up reactive bindings
 * via @fobx/dom's reactive utilities. This is the heart of the JSX transform.
 *
 * Supports:
 *   - Intrinsic HTML elements  (`<div>`, `<span>`, etc.)
 *   - Functional components    (`(props) => Node`)
 *   - Class components         (extends Component)
 *   - Fragment                 (<></>)
 *
 * @example
 * ```ts
 * // Direct usage (rare — usually generated by JSX compiler):
 * h("div", { class: "app" }, h("span", null, "Hello"))
 * ```
 */

import { el } from "../dom/element.ts"
import { appendChildNode } from "../dom/reactive.ts"
import { Component } from "./component.ts"

/**
 * Create a DOM element, functional component, or class component.
 *
 * @param tag - An HTML tag string, a functional component, or a class component.
 * @param props - Attributes / props object (may be null).
 * @param children - Variadic children.
 */
export function h(
  tag: any,
  props?: Record<string, any> | null,
  ...children: any[]
): any {
  // Merge props.children with variadic children (JSX runtime compat)
  if (props?.children != null) {
    if (Array.isArray(children) && children.length === 0) {
      children = Array.isArray(props.children)
        ? props.children
        : [props.children]
    }
  }

  // ── Fragment ───────────────────────────────────────────────────────────
  if (typeof tag === "function" && tag === Fragment) {
    return tag({ ...props, children })
  }

  // ── Class Component ────────────────────────────────────────────────────
  if (typeof tag === "function" && tag.prototype instanceof Component) {
    const instance = new tag({ ...props, children })
    const rendered = instance.render()
    const elements = Array.isArray(rendered)
      ? rendered
      : rendered
      ? [rendered]
      : []
    instance._elements = elements

    // Call ref with instance
    if (props?.ref) props.ref(instance)

    // Schedule didMount
    queueMicrotask(() => instance.didMount())

    return elements.length === 1 ? elements[0] : wrapInFragment(elements)
  }

  // ── Functional Component ───────────────────────────────────────────────
  if (typeof tag === "function") {
    return tag({ ...props, children })
  }

  // ── Intrinsic HTML Element ─────────────────────────────────────────────
  if (typeof tag === "string") {
    return el(tag, props ?? null, ...children)
  }

  throw new Error(`[@fobx/jsx] h(): unsupported tag type: ${typeof tag}`)
}

function wrapInFragment(nodes: Node[]): DocumentFragment {
  const frag = document.createDocumentFragment()
  for (const node of nodes) frag.appendChild(node)
  return frag
}

// Import Fragment here so h can reference it for identity checks
import { Fragment } from "./fragment.ts"
export { Fragment }
