/**
 * Named factory functions for every standard HTML element.
 *
 * Each function is a thin wrapper around `el(tag, props, ...children)`.
 * Usage:
 *   div({ class: "container" }, "Hello ", () => name.get())
 */

import type { Children, Props } from "./types.ts"
import { el } from "./element.ts"

type Factory = (props?: Props | null, ...children: Children[]) => HTMLElement

function factory(tag: string): Factory {
  return (props?: Props | null, ...children: Children[]) =>
    el(tag, props, ...children)
}

// ─── Standard HTML Element Factories ─────────────────────────────────────────

export const a = factory("a")
export const abbr = factory("abbr")
export const address = factory("address")
export const area = factory("area")
export const article = factory("article")
export const aside = factory("aside")
export const audio = factory("audio")
export const b = factory("b")
export const base = factory("base")
export const bdi = factory("bdi")
export const bdo = factory("bdo")
export const blockquote = factory("blockquote")
export const body = factory("body")
export const br = factory("br")
export const button = factory("button")
export const canvas = factory("canvas")
export const caption = factory("caption")
export const cite = factory("cite")
export const code = factory("code")
export const col = factory("col")
export const colgroup = factory("colgroup")
export const data = factory("data")
export const datalist = factory("datalist")
export const dd = factory("dd")
export const del = factory("del")
export const details = factory("details")
export const dfn = factory("dfn")
export const dialog = factory("dialog")
export const div = factory("div")
export const dl = factory("dl")
export const dt = factory("dt")
export const em = factory("em")
export const embed = factory("embed")
export const fieldset = factory("fieldset")
export const figcaption = factory("figcaption")
export const figure = factory("figure")
export const footer = factory("footer")
export const form = factory("form")
export const h1 = factory("h1")
export const h2 = factory("h2")
export const h3 = factory("h3")
export const h4 = factory("h4")
export const h5 = factory("h5")
export const h6 = factory("h6")
export const head = factory("head")
export const header = factory("header")
export const hgroup = factory("hgroup")
export const hr = factory("hr")
export const html = factory("html")
export const i = factory("i")
export const iframe = factory("iframe")
export const img = factory("img")
export const input = factory("input")
export const ins = factory("ins")
export const kbd = factory("kbd")
export const label = factory("label")
export const legend = factory("legend")
export const li = factory("li")
export const link = factory("link")
export const main = factory("main")
export const mark = factory("mark")
export const menu = factory("menu")
export const meta = factory("meta")
export const meter = factory("meter")
export const nav = factory("nav")
export const noscript = factory("noscript")
export const object = factory("object")
export const ol = factory("ol")
export const optgroup = factory("optgroup")
export const option = factory("option")
export const output = factory("output")
export const p = factory("p")
export const picture = factory("picture")
export const pre = factory("pre")
export const progress = factory("progress")
export const q = factory("q")
export const rp = factory("rp")
export const rt = factory("rt")
export const ruby = factory("ruby")
export const s = factory("s")
export const samp = factory("samp")
export const script = factory("script")
export const search = factory("search")
export const section = factory("section")
export const select = factory("select")
export const slot = factory("slot")
export const small = factory("small")
export const source = factory("source")
export const span = factory("span")
export const strong = factory("strong")
export const style = factory("style")
export const sub = factory("sub")
export const summary = factory("summary")
export const sup = factory("sup")
export const table = factory("table")
export const tbody = factory("tbody")
export const td = factory("td")
export const template = factory("template")
export const textarea = factory("textarea")
export const tfoot = factory("tfoot")
export const th = factory("th")
export const thead = factory("thead")
export const time = factory("time")
export const title = factory("title")
export const tr = factory("tr")
export const track = factory("track")
export const u = factory("u")
export const ul = factory("ul")
// `var` is a reserved word in JS
export const varEl = factory("var")
export const video = factory("video")
export const wbr = factory("wbr")
